version: "3.8"
services:
  override:
    build: .
    platform: linux/amd64
    image: minseohong/override
    container_name: override
    ports:
      - ${PORT_MAPPING}
    volumes:
      - .:/code
    environment:
      - PYTHONUNBUFFERED=1
    restart: always
  
  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/ssl/certs
      - ./keys:/etc/ssl/private
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    restart: always
