version: "3.8"
services:
  override:
    build: .
    platform: linux/amd64
    image: minseohong/override
    container_name: override
    ports:
      - ${PORT_MAPPING}
    volumes:
      - .:/code
    environment:
      - PYTHONUNBUFFERED=1
